# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Greenwood Project
email: adamwustl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Introducing minority students to the financial industry
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://greenwoodproject.org" # the base hostname & protocol for your site
twitter_username: greenwoodprochi
github_username:  subrb

# Build settings
markdown: kramdown
