---
title: Greenwood Project
timezone: UTC
<<<<<<< HEAD
hs_applications_open: false
college_applications_open: true
year-stats:
- year: 2016
  path: "/assets/img/graph_2016.png"
  text: 120 Students and 8 Firms
- year: 2017
  path: "/assets/img/graph_2017.png"
  text: 180 Students and 12 Firms
- year: 2018
  path: "/assets/img/graph_2018.png"
  text: 225 Students and 24 Firms
=======
>>>>>>> 3ef9c5c47bbfe4c153e0acf7e86f85e7f62415ab
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
year-stats:
- year: 2016
  path: "/assets/img/graph_2016.png"
  text: 120 Students and 8 Firms
- year: 2017
  path: "/assets/img/graph_2017.png"
  text: 180 Students and 12 Firms
- year: 2018
  path: "/assets/img/graph_2018.png"
  text: 225 Students and 24 Firms
permalink: pretty
